### ISSUE TITLE
Example Build Error with ESP32 and Arduino 1.8

### ISSUE THREAD

**Issue by riodda** [MajicDesigns/MD_REncoder#2]
In file included from D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src\MD_REncoder.cpp:30:0:

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src/MD_REncoder.h: In constructor 'MD_REncoder::MD_REncoder(uint8_t, uint8_t)':

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src/MD_REncoder.h:259:15: error: 'MD_REncoder::_spd' will be initialized after [-Werror=reorder]

     uint16_t  _spd;     // last calculated speed (no sign) in clicks/second

               ^

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src/MD_REncoder.h:258:15: error:   'uint16_t MD_REncoder::_count' [-Werror=reorder]

     uint16_t  _count;   // running count of encoder clicks

               ^

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src\MD_REncoder.cpp:80:1: error:   when initialized here [-Werror=reorder]

 MD_REncoder::MD_REncoder(uint8_t pinA, uint8_t pinB):

 ^

In file included from D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src\MD_REncoder.cpp:30:0:

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src/MD_REncoder.h:258:15: error: 'MD_REncoder::_count' will be initialized after [-Werror=reorder]

     uint16_t  _count;   // running count of encoder clicks

               ^

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src/MD_REncoder.h:257:15: error:   'uint16_t MD_REncoder::_period' [-Werror=reorder]

     uint16_t  _period;  // velocity calculation period

               ^

D:\Users\Precision 7510 Dario\Documents\Arduino\libraries\MD_REncoder\src\MD_REncoder.cpp:80:1: error:   when initialized here [-Werror=reorder]

 MD_REncoder::MD_REncoder(uint8_t pinA, uint8_t pinB):

 ^

cc1plus.exe: some warnings being treated as errors

Più di una libreria trovata per "MD_REncoder.h"
Usata: D:\Users\Precision
Uso la libreria MD_REncoder alla versione 1.0 nella cartella: D:\Users\Precision 7510
exit status 1
Errore durante la compilazione per la scheda WEMOS LOLIN32.

**Comment by MajicDesigns** [comment]
This error was **not** duplicated using WEMOS LOLIN32, IDE 1.8.10, Windows 10.

However these errors are caused by unnecessarily picky compiler setting for some hardware types causing warnings to be treated as errors:

> cc1plus.exe: some warnings being treated as errors

This warnings/error refers to the class initializers not being in the same order as the class declarations. This has been changed and issued as version 1.0.1.

Please also note that you may have more than one copy of the library installed and this may be affecting your compilation:

> Più di una libreria trovata per "MD_REncoder.h"
> Usata: D:\Users\Precision
> Uso la libreria MD_REncoder alla versione 1.0 nella cartella: D:\Users\Precision 7510
